# ---------------------------------------------------------
# CONFIGURACIÓN GENERAL DE LA APLICACIÓN
# ---------------------------------------------------------

# Nombre lógico de la aplicación dentro de Spring Boot
spring.application.name=biblioteca

# Puerto en el que se ejecutará la aplicación
server.port=8081


# ---------------------------------------------------------
# CONFIGURACIÓN DE CONEXIÓN A ORACLE
# ---------------------------------------------------------

# URL de conexión JDBC a Oracle
# Formato:
# jdbc:oracle:thin:@//host:puerto/serviceName
#spring.datasource.url=jdbc:oracle:thin:@//localhost:1521/XEPDB1
spring.datasource.url=jdbc:oracle:thin:@qbb60z7j0xapcye9_tp?TNS_ADMIN=C:/Users/Rodolfo/Desktop/Duoc/Asignaturas/Desarrollo_Full_Stack_III/Wallet/Wallet_QBB60Z7J0XAPCYE9
#spring.datasource.url=jdbc:oracle:thin:@qbb60z7j0xapcye9_tp?TNS_ADMIN=/apps/Wallet
# Usuario de la base de datos Oracle
spring.datasource.username=ADMIN

# Contraseña del usuario Oracle
spring.datasource.password=Arafat232323

# Driver JDBC que usará Spring para conectarse a Oracle
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver


# ---------------------------------------------------------
# CONFIGURACIÓN DE JPA / HIBERNATE
# ---------------------------------------------------------

# Indica que Hibernate NO debe crear ni modificar tablas
# Se usa "none" porque la tabla ya existe en Oracle
spring.jpa.hibernate.ddl-auto=none

# Muestra en consola las sentencias SQL ejecutadas
spring.jpa.show-sql=true

# Formatea el SQL mostrado en consola para hacerlo más legible
spring.jpa.properties.hibernate.format_sql=true

# Dialecto de Hibernate para Oracle
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
